ETrade/MvcWebUI/Models/CartListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Entities.DomainModels;

namespace MvcWebUI.Models
{
    public class CartListViewModel
    {
        public Cart Cart { get; set; }
    }
}

ETrade/MvcWebUI/Models/CategoryListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Entities.Concrete;

namespace MvcWebUI.Models
{
    public class CategoryListViewModel
    {
        public List<Category> Categories { get; set; }
        public int CurrentCategory { get; internal set; }
    }
}

ETrade/MvcWebUI/Models/CustomerListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Entities.Concrete;

namespace MvcWebUI.Models
{
    public class CustomerListViewModel
    {
        public List<Customer> Customers { get; set; }
    }
}

ETrade/MvcWebUI/Models/ErrorViewModel.cs
using System;

namespace MvcWebUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ETrade/MvcWebUI/Models/ProductListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Entities.Concrete;

namespace MvcWebUI.Models
{
    public class ProductListViewModel
    {
        public List<Product> Products { get; set; }

    }
}

ETrade/MvcWebUI/Models/ShippingDetail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcWebUI.Models
{
    public class ShippingDetail
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public int Age { get; set; }
    }
}

ETrade/MvcWebUI/Models/ShippingDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcWebUI.Models
{
    public class ShippingDetailViewModel
    {
        public ShippingDetail ShippingDetail { get; set; }
    }
}

ETrade/MvcWebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Business.Abstract;
using Entities.Concrete;
using Microsoft.AspNetCore.Mvc;
using MvcWebUI.Helpers;
using MvcWebUI.Models;

namespace MvcWebUI.Controllers
{
    public class CartController:Controller
    {
        private ICartService _cartService;
        private ICartSessionHelper _cartSessionHelper;
        private IProductService _productService;

        public CartController(ICartService cartService, ICartSessionHelper cartSessionHelper, IProductService productService)
        {
            _cartService = cartService;
            _cartSessionHelper = cartSessionHelper;
            _productService = productService;
        }

        public IActionResult AddToCart(int productId)
        {

            Product product = _productService.GetById(productId);

            var cart = _cartSessionHelper.GetCart("cart");

            _cartService.AddToCart(cart,product);

            _cartSessionHelper.SetCart("cart",cart);

            TempData.Add("message",product.ProductName + " sepete eklendi!");

            return RedirectToAction("Index", "Product");
        }

        public IActionResult RemoveFromCart(int productId)
        {
            Product product = _productService.GetById(productId);

            var cart = _cartSessionHelper.GetCart("cart");

            _cartService.RemoveFromCart(cart,productId);
            _cartSessionHelper.SetCart("cart",cart);

            TempData.Add("message", product.ProductName + " sepetten silindi!");

            return RedirectToAction("Index", "Cart");
        }

        public IActionResult Index()
        {
            var model = new CartListViewModel
            {
                Cart = _cartSessionHelper.GetCart("cart")
            };

            return View(model);
        }

        public IActionResult Complete()
        {
            var model = new ShippingDetailViewModel
            {
                ShippingDetail = new ShippingDetail()
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Complete(ShippingDetail shippingDetail)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            TempData.Add("message","Siparişiniz Başarıyla Tamamlandı.");
            _cartSessionHelper.Clear();
            return RedirectToAction("Index", "Cart");
        }

    }
}

ETrade/MvcWebUI/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using MvcWebUI.Models;

namespace MvcWebUI.Controllers
{
    public class CategoryController : Controller
    {
        private ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public IActionResult Index()
        {
            var model = new CategoryListViewModel
            {
                Categories = _categoryService.GetAll()
            };
            return View(model);
        }
    }
}

ETrade/MvcWebUI/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using MvcWebUI.Models;

namespace MvcWebUI.Controllers
{
    public class CustomerController : Controller
    {
        private ICustomerService _customerService;

        public CustomerController(ICustomerService customerService)
        {
            _customerService = customerService;
        }

        public IActionResult Index()
        {
            var model = new CustomerListViewModel
            {
                Customers = _customerService.GetAll()
            };
            return View(model);
            
        }
    }
}

ETrade/MvcWebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcWebUI.Models;

namespace MvcWebUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ETrade/MvcWebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using MvcWebUI.Models;

namespace MvcWebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        public IActionResult Index(int category)
        {
            var model = new ProductListViewModel
            {
                Products = category>0? _productService.GetByCategory(category):_productService.GetAll()
            };
            return View(model);
        }
    }
}

ETrade/MvcWebUI/ViewComponents/CategoryListViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using MvcWebUI.Models;

namespace MvcWebUI.ViewComponents
{
    public class CategoryListViewComponent:ViewComponent
    {
        private ICategoryService _categoryService;

        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public ViewViewComponentResult Invoke()
        {
            var model = new CategoryListViewModel
            {
                Categories = _categoryService.GetAll(),
                CurrentCategory = Convert.ToInt32(HttpContext.Request.Query["category"])
            };
            return View(model);
        }
    }
}

ETrade/MvcWebUI/Views/Cart/Complete.cshtml
@model ShippingDetailViewModel

    <form asp-controller="Cart" asp-action="Complete">

        <div class="form-group">
            <label asp-for="ShippingDetail.FirstName">Ad</label>
            <input asp-for="ShippingDetail.FirstName" class="form-control" placeholder="Müşteri Adınız" />
            <span asp-validation-for="ShippingDetail.FirstName"></span>
        </div>

        <div class="form-group">
            <label asp-for="ShippingDetail.LastName">Soyad</label>
            <input asp-for="ShippingDetail.LastName" class="form-control" placeholder="Müşteri Soyadınız" />
            <span asp-validation-for="ShippingDetail.LastName"></span>
        </div>
        
        <div class="form-group">
            <label asp-for="ShippingDetail.Email">E-Mail</label>
            <input asp-for="ShippingDetail.Email" class="form-control" placeholder="E-Mail Hesabınız"/>
            <span asp-validation-for="ShippingDetail.Email"></span>
        </div>
        
        <div class="form-group">
            <label asp-for="ShippingDetail.Age">Yaş</label>
            <input asp-for="ShippingDetail.Age" class="form-control" placeholder="Yaşınız"/>
            <span asp-validation-for="ShippingDetail.Age"></span>
        </div>
        
        <div class="form-group">
            <label asp-for="ShippingDetail.City">Şehir</label>
            <input asp-for="ShippingDetail.City" class="form-control" placeholder="Şehriniz"/>
            <span asp-validation-for="ShippingDetail.City"></span>
        </div>
        
        <div class="form-group">
            <label asp-for="ShippingDetail.Address">Adres</label>
            <input asp-for="ShippingDetail.Address" class="form-control" placeholder="Adresiniz"/>
            <span asp-validation-for="ShippingDetail.Address"></span>
        </div>
        
        <input type="submit" value="Kaydet" class="btn btn-success"/>
    </form>

ETrade/MvcWebUI/Views/Cart/Index.cshtml
@using Entities.Concrete
@model CartListViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Sepet</h2>

@if (Model.Cart.CartLines.Count == 0)
{
    <h2 class="badge badge-danger">Sepet Boş</h2>
}
else
{
    <table class="table table-responsive">
        <thead>
        <tr>
            <th>Product Name</th>
            <th>Price</th>
            <th>Stock</th>
            <th>Quantity</th>
        </tr>
        </thead>
        @foreach (var cartLine in Model.Cart.CartLines)
        {
            <tr>
                <td>@cartLine.Product.ProductName</td>
                <td>@cartLine.Product.ProductPrice</td>
                <td>@cartLine.Product.ProductStock</td>
                <td>@cartLine.Product.ProductQuantity</td>
                <td><a class="btn btn-sm btn-danger" asp-controller="Cart" asp-action="RemoveFromCart" asp-route-productId="@cartLine.Product.ProductId">Sil</a></td>
            </tr>
        }

       
    </table>

    <a class="btn btn-sm btn-success" asp-controller="Cart" asp-action="Complete">Alışverişi Tamamla</a>
}

ETrade/MvcWebUI/Views/Customer/Index.cshtml
@model CustomerListViewModel

@{
    ViewBag.Title = "title";
}

<h2>Customer List</h2>

<table class="table table-responsive">
    @foreach (var customer in Model.Customers)
    {
    <tr>
        <td>@customer.CustomerFirstName</td>
        <td>@customer.CustomerLastName</td>
        <td>@customer.CustomerAddress</td>
        <td>@customer.CustomerCity</td>
    </tr>
    }
</table>

ETrade/MvcWebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ETrade/MvcWebUI/Views/Product/Index.cshtml
@model ProductListViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Ürünler</h2>

<table class="table table-responsive">
    @foreach (var product in Model.Products)
    {
    <tr>
        <td>@product.ProductName</td>
        <td>@product.ProductPrice</td>
        <td>@product.ProductStock</td>
        <td>@product.ProductQuantity</td>
        <td><a class="btn btn-sm btn-success" asp-controller="Cart" asp-action="AddToCart" asp-route-productId="@product.ProductId">Sepete Ekle</a></td>
    </tr>
    }
</table>

ETrade/MvcWebUI/Views/Shared/Components/CategoryList/Default.cshtml
@model MvcWebUI.Models.CategoryListViewModel



<h2>Kategoriler</h2>

<div class="list-group">
    <a href="/product/index" class="list-group-item">Tüm Ürünler</a>
    @foreach (var category in Model.Categories)
    {
        var css = "list-group-item";
        if (category.CategoryId == Model.CurrentCategory)
        {
            css += " active";
        }
        <a href="/product/index?category=@category.CategoryId" class="@css">@category.CategoryName</a>
    }
</div>

ETrade/MvcWebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcWebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcWebUI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Sepet</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="row">
                
                @if (TempData["message"] !=null)
                {
                    <div class="alert alert-primary">
                        @TempData["message"]
                    </div>
                }

            </div>
            <div class="row">
                <div class="col-3">
                    @await Component.InvokeAsync("CategoryList")

                </div>
                <div class="col-9">@RenderBody()</div>
            </div>

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MvcWebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>